# Capstone Two


In [74]:
import pandas as pd
import matplotlib as plt
import seaborn as sns
import os

import pandas as pd
import os
import pickle
import numpy as np 
import json
import statistics

from sklearn.neighbors import KNeighborsClassifier 
from sklearn.model_selection import train_test_split 
from sklearn.datasets import load_iris 
from sklearn import datasets, linear_model
from matplotlib import pyplot as plt


data_2020= pd.read_csv('2020.csv')

# Create Dummy Variables 

In [75]:
#create dummy variables for categorical variables 
#select all the columns that are categorical, ‘object’, creating a data frame subset 
dummy = pd.get_dummies(data_2020['Country name'])
dummy2 = pd.get_dummies(data_2020['Regional indicator'])

In [76]:
dummy.head()

Afghanistan  Albania  Algeria  Argentina  Armenia  Australia  Austria  \
0            0        0        0          0        0          0        0   
1            0        0        0          0        0          0        0   
2            0        0        0          0        0          0        0   
3            0        0        0          0        0          0        0   
4            0        0        0          0        0          0        0   

   Azerbaijan  Bahrain  Bangladesh  ...  United Arab Emirates  United Kingdom  \
0           0        0           0  ...                     0               0   
1           0        0           0  ...                     0               0   
2           0        0           0  ...                     0               0   
3           0        0           0  ...                     0               0   
4           0        0           0  ...                     0               0   

   United States  Uruguay  Uzbekistan  Venezuela  Vietnam  Yemen  Zambia  \
0              0        0           0          0        0      0       0   
1              0        0           0          0        0      0       0   
2              0        0           0          0        0      0       0   
3              0        0           0          0        0      0       0   
4              0        0           0          0        0      0       0   

   Zimbabwe  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 153 columns]

In [77]:
dummy2.head()

Central and Eastern Europe  Commonwealth of Independent States  East Asia  \
0                           0                                   0          0   
1                           0                                   0          0   
2                           0                                   0          0   
3                           0                                   0          0   
4                           0                                   0          0   

   Latin America and Caribbean  Middle East and North Africa  \
0                            0                             0   
1                            0                             0   
2                            0                             0   
3                            0                             0   
4                            0                             0   

   North America and ANZ  South Asia  Southeast Asia  Sub-Saharan Africa  \
0                      0           0               0                   0   
1                      0           0               0                   0   
2                      0           0               0                   0   
3                      0           0               0                   0   
4                      0           0               0                   0   

   Western Europe  
0               1  
1               1  
2               1  
3               1  
4               1

In [78]:
#concatenate the original data frame df 
#Concat new columns to original dataframe 
df_concat = pd.concat([data_2020, dummy2, dummy], axis=1)
print (df_concat.head())

  Country name Regional indicator  Ladder score  \
0      Finland     Western Europe        7.8087   
1      Denmark     Western Europe        7.6456   
2  Switzerland     Western Europe        7.5599   
3      Iceland     Western Europe        7.5045   
4       Norway     Western Europe        7.4880   

   Standard error of ladder score  upperwhisker  lowerwhisker  \
0                        0.031156      7.869766      7.747634   
1                        0.033492      7.711245      7.579955   
2                        0.035014      7.628528      7.491272   
3                        0.059616      7.621347      7.387653   
4                        0.034837      7.556281      7.419719   

   Logged GDP per capita  Social support  Healthy life expectancy  \
0              10.639267        0.954330                71.900825   
1              10.774001        0.955991                72.402504   
2              10.979933        0.942847                74.102448   
3              10.772559  

In [79]:
#Drop corresponding categorical columns and first dummy variable columns.

df_concat.drop(['Country name','Regional indicator'], inplace=True, axis=1)
print(df_concat.head())

   Ladder score  Standard error of ladder score  upperwhisker  lowerwhisker  \
0        7.8087                        0.031156      7.869766      7.747634   
1        7.6456                        0.033492      7.711245      7.579955   
2        7.5599                        0.035014      7.628528      7.491272   
3        7.5045                        0.059616      7.621347      7.387653   
4        7.4880                        0.034837      7.556281      7.419719   

   Logged GDP per capita  Social support  Healthy life expectancy  \
0              10.639267        0.954330                71.900825   
1              10.774001        0.955991                72.402504   
2              10.979933        0.942847                74.102448   
3              10.772559        0.974670                73.000000   
4              11.087804        0.952487                73.200783   

   Freedom to make life choices  Generosity  Perceptions of corruption  ...  \
0                      0.949172

In [86]:
#check info on data to check categorical variables are gone.

df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Columns: 181 entries, Ladder score to Zimbabwe
dtypes: float64(18), uint8(163)
memory usage: 46.0 KB


In [90]:
# saving the new dataframe
df_concat.to_csv('concat_happiness.csv')

# Split into testing and training datasets 


In [62]:
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
import numpy as np

#train_test_split()
# spliting training and testing data
#x= data, y=target dependent variable

X = data_2020
y = data_2020

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=27)

In [63]:
print("shape of original dataset :", data_2020.shape)
print("shape of input - training set", X_train.shape)
print("shape of output - training set", y_train.shape)
print("shape of input - testing set", X_test.shape)
print("shape of output - testing set", y_test.shape)

shape of original dataset : (153, 20)
shape of input - training set (122, 20)
shape of output - training set (122, 20)
shape of input - testing set (31, 20)
shape of output - testing set (31, 20)


In [24]:
#train_test_split()
# spliting training and testing data
#x= data, y=target dependent variable

X = all_happiness_data
y = all_happiness_data.GDP

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=27)

In [65]:
print("shape of original dataset :", data_2020.shape)
print("shape of input - training set", X_train.shape)
print("shape of output - training set", y_train.shape)
print("shape of input - testing set", X_test.shape)
print("shape of output - testing set", y_test.shape)

shape of original dataset : (153, 20)
shape of input - training set (122, 20)
shape of output - training set (122, 20)
shape of input - testing set (31, 20)
shape of output - testing set (31, 20)


In [66]:
#what is the mean of training data

print(X_train.mean())

Ladder score                                   5.544606
Standard error of ladder score                 0.051898
upperwhisker                                   5.646325
lowerwhisker                                   5.442887
Logged GDP per capita                          9.361937
Social support                                 0.816999
Healthy life expectancy                       65.326383
Freedom to make life choices                   0.794421
Generosity                                    -0.014337
Perceptions of corruption                      0.723100
Ladder score in Dystopia                       1.972317
Explained by: Log GDP per capita               0.889299
Explained by: Social support                   1.175158
Explained by: Healthy life expectancy          0.724581
Explained by: Freedom to make life choices     0.476840
Explained by: Generosity                       0.189528
Explained by: Perceptions of corruption        0.137187
Dystopia + residual                            1

In [67]:
print(y_train.mean())

Ladder score                                   5.544606
Standard error of ladder score                 0.051898
upperwhisker                                   5.646325
lowerwhisker                                   5.442887
Logged GDP per capita                          9.361937
Social support                                 0.816999
Healthy life expectancy                       65.326383
Freedom to make life choices                   0.794421
Generosity                                    -0.014337
Perceptions of corruption                      0.723100
Ladder score in Dystopia                       1.972317
Explained by: Log GDP per capita               0.889299
Explained by: Social support                   1.175158
Explained by: Healthy life expectancy          0.724581
Explained by: Freedom to make life choices     0.476840
Explained by: Generosity                       0.189528
Explained by: Perceptions of corruption        0.137187
Dystopia + residual                            1

In [32]:
#what is the STD of the training data

print(X_train.std())

Happiness Score                               1.115786e+00
Standard error of ladder score                1.959381e-02
upperwhisker                                  1.126050e+00
lowerwhisker                                  1.160814e+00
GDP                                           3.165449e+00
Family                                        3.116965e-01
Life Expectancy                               2.385765e+01
Freedom                                       2.038308e-01
Generosity                                    1.513460e-01
Trust                                         2.557612e-01
Ladder score in Dystopia                      2.675523e-15
Explained by: Log GDP per capita              3.839834e-01
Explained by: Social support                  2.965560e-01
Explained by: Healthy life expectancy         2.534086e-01
Explained by: Freedom to make life choices    1.412818e-01
Explained by: Generosity                      9.946854e-02
Explained by: Perceptions of corruption       1.157491e-

In [68]:
print(y_train.std())

Ladder score                                  1.141086e+00
Standard error of ladder score                1.680128e-02
upperwhisker                                  1.129515e+00
lowerwhisker                                  1.153481e+00
Logged GDP per capita                         1.154128e+00
Social support                                1.141562e-01
Healthy life expectancy                       6.597897e+00
Freedom to make life choices                  1.172909e-01
Generosity                                    1.545184e-01
Perceptions of corruption                     1.838787e-01
Ladder score in Dystopia                      2.675523e-15
Explained by: Log GDP per capita              3.577063e-01
Explained by: Social support                  2.696304e-01
Explained by: Healthy life expectancy         2.375346e-01
Explained by: Freedom to make life choices    1.405788e-01
Explained by: Generosity                      1.021932e-01
Explained by: Perceptions of corruption       1.187177e-

# Standardize the magnitude of numeric features using a scale

In [88]:
# the scaler object (model)
scaler = StandardScaler()

# fit and transform the data
scaled_data = scaler.fit_transform(df_concat) 

print(scaled_data)

[[ 2.10661952 -1.23498     2.09615988 ... -0.08111071 -0.08111071
  -0.08111071]
 [ 1.9595007  -1.10608761  1.95115724 ... -0.08111071 -0.08111071
  -0.08111071]
 [ 1.88219801 -1.02211458  1.87549456 ... -0.08111071 -0.08111071
  -0.08111071]
 ...
 [-1.96101593  0.28338899 -1.97942562 ... -0.08111071 -0.08111071
  12.32882801]
 [-2.39632821  2.98352683 -2.33313396 ... -0.08111071 -0.08111071
  -0.08111071]
 [-2.62156135 -1.22642089 -2.6983315  ... -0.08111071 -0.08111071
  -0.08111071]]


In [44]:
#Verify that the mean of each feature (column) is 0:

scaled_data.mean(axis = 0)
#array([0., 0.])

array([-6.03729122e-16,  2.55423859e-16, -4.64407017e-16, -4.64407017e-16,
        0.00000000e+00, -7.89491929e-16,  2.32203508e-16,  0.00000000e+00,
       -1.16101754e-17,  1.62542456e-16,  0.00000000e+00,  2.78644210e-16,
       -3.71525613e-16,  1.39322105e-16,  5.57288420e-16,  2.84449298e-16,
        0.00000000e+00,  6.26949473e-16])

In [47]:
#Verify that the std of each feature (column) is 1:

scaled_data.std(axis = 0)
#array([1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1.])

# Review the following questions and apply them to your dataset:

- Does my data set have any categorical data, such as Gender or day of the week?

Yes, Country and Region. 

- Do my features have data values that range from 0 - 100 or 0-1 or both and more? 

Yes, both. Features like GDP, Healthy life expectancy are 0-100, Ladder Score is 0-10, and Social Support, Genorosity and the majority of the other features are on a 0-1 scale. 